name: Bug Report
description: Report a bug of Shizuku
labels: bug

body:
  - type: checkboxes
    id: read_wiki
    attributes:
      label: Wiki
      description: Please read the [wiki](https://example.com) and follow all relevant troubleshooting steps before creating an issue 
      options:
        - label: I read the wiki and followed all troubleshooting steps
          required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      options:
        - label: Shizuku is downloaded from official channels (GitHub release or Google Play)
        - label: Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
        - label: (Root users) No Xposed installed / Xposed is not enabled for Shizuku

  - type: input
    id: version
    attributes:
      label: Latest Shizuku Version
    validations:
      required: true

  - type: checkboxes
    id: shizuku_version
    attributes:
      label: Version In Use
      options:
        - label: I am using the latest version of Shizuku
          required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode
      options:
        - adb
        - root
        - manual
    validations:
      required: true

  - type: input
    id: android_version
    attributes:
      label: Android Version
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Issue Description
      description: Please upload any relevant logs and/or screenshots

  - type: textarea
    id: reproducer
    attributes:
      label: Steps To Reproduce