name: Feature Request
description: Suggest an idea for this project
labels: enhancement

body:
  - type: checkboxes
    id: before_you_begin
    attributes:
      label: Before You Begin
      options:
        - label: I searched through all [open/closed issues](https://github.com/thedjchi/Shizuku/issues) and confirmed that this is a new feature request
          required: true
        - label: I am using the latest version of Shizuku
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe the problem your proposed feature would address. E.g., I'm always frustrated when [...]

  - type: textarea
    id: solution
    attributes:
      label: Ideal Solution
      description: Describe your ideal solution/feature

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here